package com.myspace.bre_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RLCustomer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;

	private java.lang.Boolean isJuvenile;

	private java.lang.String customerId;

	private java.lang.Boolean isForeigner;

	private java.lang.Boolean isModifyDetail;

	private java.lang.Boolean isChangeAddress;

	private java.lang.Boolean isBlacklisted;

	private java.lang.Boolean hasSponsor;

	private java.lang.Boolean hasNewSponsor;

	private java.lang.Boolean isBlackListFraud;

	private java.lang.String message;

	public RLCustomer() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getIsJuvenile() {
		return this.isJuvenile;
	}

	public void setIsJuvenile(java.lang.Boolean isJuvenile) {
		this.isJuvenile = isJuvenile;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.Boolean getIsForeigner() {
		return this.isForeigner;
	}

	public void setIsForeigner(java.lang.Boolean isForeigner) {
		this.isForeigner = isForeigner;
	}

	public java.lang.Boolean getIsModifyDetail() {
		return this.isModifyDetail;
	}

	public void setIsModifyDetail(java.lang.Boolean isModifyDetail) {
		this.isModifyDetail = isModifyDetail;
	}

	public java.lang.Boolean getIsChangeAddress() {
		return this.isChangeAddress;
	}

	public void setIsChangeAddress(java.lang.Boolean isChangeAddress) {
		this.isChangeAddress = isChangeAddress;
	}

	public java.lang.Boolean getIsBlacklisted() {
		return this.isBlacklisted;
	}

	public void setIsBlacklisted(java.lang.Boolean isBlacklisted) {
		this.isBlacklisted = isBlacklisted;
	}

	public java.lang.Boolean getHasSponsor() {
		return this.hasSponsor;
	}

	public void setHasSponsor(java.lang.Boolean hasSponsor) {
		this.hasSponsor = hasSponsor;
	}

	public java.lang.Boolean getHasNewSponsor() {
		return this.hasNewSponsor;
	}

	public void setHasNewSponsor(java.lang.Boolean hasNewSponsor) {
		this.hasNewSponsor = hasNewSponsor;
	}

	public java.lang.Boolean getIsBlackListFraud() {
		return this.isBlackListFraud;
	}

	public void setIsBlackListFraud(java.lang.Boolean isBlackListFraud) {
		this.isBlackListFraud = isBlackListFraud;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public RLCustomer(java.lang.Integer age, java.lang.Boolean isJuvenile,
			java.lang.String customerId, java.lang.Boolean isForeigner,
			java.lang.Boolean isModifyDetail,
			java.lang.Boolean isChangeAddress, java.lang.Boolean isBlacklisted,
			java.lang.Boolean hasSponsor, java.lang.Boolean hasNewSponsor,
			java.lang.Boolean isBlackListFraud, java.lang.String message) {
		this.age = age;
		this.isJuvenile = isJuvenile;
		this.customerId = customerId;
		this.isForeigner = isForeigner;
		this.isModifyDetail = isModifyDetail;
		this.isChangeAddress = isChangeAddress;
		this.isBlacklisted = isBlacklisted;
		this.hasSponsor = hasSponsor;
		this.hasNewSponsor = hasNewSponsor;
		this.isBlackListFraud = isBlackListFraud;
		this.message = message;
	}

}